[workspace]
members = [
    "crates/bjj-ecdsa-nova-wasm",
    "crates/bjj-ecdsa-nova-params",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

[workspace.dependencies]
ahash = "0.8.7"
flate2 = "1.0.28"
nova-scotia = { git = "https://github.com/Mach-34/Nova-Scotia/" }
nova-snark = "0.23.0"
serde = "1.0.190"
serde_json = "1.0.107"