

# This file was *autogenerated* from the file sage/bjj-mont-to-sw.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_9 = Integer(9); _sage_const_27 = Integer(27); _sage_const_21888242871839275222246405745257275088614511777268538073601725287587578984328 = Integer(21888242871839275222246405745257275088614511777268538073601725287587578984328); _sage_const_2736030358979909402780800718157159386076813972158567259200215660948447373041 = Integer(2736030358979909402780800718157159386076813972158567259200215660948447373041); _sage_const_7296080957279758407415468581752425029516121466805344781232734728858602888112 = Integer(7296080957279758407415468581752425029516121466805344781232734728858602888112); _sage_const_4258727773875940690362607550498304598101071202821725296872974770776423442226 = Integer(4258727773875940690362607550498304598101071202821725296872974770776423442226); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0)
def montgomery_to_weierstrass(A, p):
    # from https://safecurves.cr.yp.to/equation.html
    
    # Define the finite field
    Fp = GF(p)
    
    # Do the calculations in the finite field
    A = Fp(A)
    three = Fp(_sage_const_3 )
    two = Fp(_sage_const_2 )
    nine = Fp(_sage_const_9 )
    twenty_seven = Fp(_sage_const_27 )
    
    a = (three - A**_sage_const_2 ) / three
    b = (two*A**_sage_const_3  - nine*A) / (twenty_seven)
    
    return a, b

  # Define your Montgomery curve parameter and the prime for the finite field
A = "168698"
p = "21888242871839275222246405745257275088548364400416034343698204186575808495617" 

# Convert to Weierstrass form
a, b = montgomery_to_weierstrass(A, p)

print("Curve params")
print("a", hex(a))
print("b", hex(b))
print("p", hex(int(p)))
print()

# Now you can define your Weierstrass curve
E = EllipticCurve(GF(p), [a, b])

# Validate order of curve
curve_order = E.order()
print("Curve order verification")
print("order", hex(curve_order))

if curve_order == _sage_const_21888242871839275222246405745257275088614511777268538073601725287587578984328 :
    print("This is the correct order!")
else:
    print("This is the wrong order!")
print()

# Create a base point
print("Main subgroup order", hex(int(_sage_const_2736030358979909402780800718157159386076813972158567259200215660948447373041 )))
P = E(_sage_const_7296080957279758407415468581752425029516121466805344781232734728858602888112 , _sage_const_4258727773875940690362607550498304598101071202821725296872974770776423442226 ) 
base = _sage_const_8  * P
base_order = curve_order / _sage_const_8 

if base.order().is_prime() and base.order() == _sage_const_2736030358979909402780800718157159386076813972158567259200215660948447373041 :
    print("Example base point")
    print(base.xy())
    print([hex(int(c)) for c in base.xy()])

# Verify signature manually
sk = Integer("0xabadbabeabadbabeabadbabeabadbabe")
msg = Integer("0xabadbabeabadbabeabadbabeabadbabe")

if sk < base_order:
    print(sk, "is a fine private key")
else:
    print(sk, "is not an okay private key")

# Manually verify signature
pk = sk * base
r = Integer("0x5ab098d6016e6f886d3deca0cb25f311f45129fe6679d19fdc7de80510fb8ea")
s = Integer("0x4c03f936209f7b00f1db3893715665ece1642a90217a60ee903d686ca2b0384")

if r >= base_order:
    print("r is too large")
if s >= base_order:
    print("s is too large")
    
w = inverse_mod(s, base_order)
u1 = (msg * w) % base_order
u2 = (r * w) % base_order
point = u1 * base + u2 * pk

if point[_sage_const_0 ] == r:
    print("The signature is valid.")
else:
    print("The signature is invalid.")

