[package]
name = "bjj_ecdsa_nova_params"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "bjj_nova_params_gen"
path = "src/main.rs"

[dependencies]
ahash.workspace = true
flate2.workspace = true
nova-snark.workspace = true
nova-scotia.workspace = true
serde_json.workspace = true

clap = { version = "4.4.7", features = ["derive"] }
